# Generated by Django 5.1 on 2024-08-27 11:58

import django.contrib.auth.models
import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=250, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superuser status')),
                ('last_login', models.DateTimeField(blank=True, verbose_name='Last Login')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to=users.models.GenerateProfilePic())),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('programming', 'Programming'), ('db_management', 'Database Management'), ('networking', 'Networking'), ('cloud_computing', 'Cloud Computing'), ('cyber_security', 'Cyber Security'), ('ui_ux_design', 'UI/UX Design'), ('graphic_design', 'Graphic Design'), ('web_design', 'Web Design'), ('motion_graphics', 'Motion Graphics'), ('illustration', 'Illustration'), ('machine_learning', 'Machine Learning'), ('deep_learning', 'Deep Learning'), ('data_analysis', 'Data Analysis'), ('nlp', 'Natural Language Processing'), ('computer_vision', 'Computer Vision')], max_length=50, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='users.profile')),
            ],
        ),
    ]
