# Generated by Django 5.1 on 2024-08-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pro_user',
            field=models.BooleanField(default=False, verbose_name='is_Pro'),
        ),
    ]
