# Generated by Django 5.1.1 on 2024-09-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='gender'),
        ),
    ]
