# Generated by Django 5.1 on 2024-08-31 00:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('design', 'Design'), ('programming', 'Programming'), ('english', 'English')], max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('desc', models.TextField()),
                ('governrate', models.CharField(choices=[('cairo', 'Cairo'), ('alexandria', 'Alexandria'), ('giza', 'Giza'), ('suez', 'Suez'), ('dakahlia', 'Dakahlia'), ('damietta', 'Damietta'), ('faiyum', 'Faiyum'), ('gharbia', 'Gharbia'), ('ismailia', 'Ismailia'), ('kafr_el_sheikh', 'Kafr El Sheikh'), ('minya', 'Minya'), ('monufia', 'Monufia'), ('qalyubia', 'Qalyubia'), ('qena', 'Qena'), ('sharqia', 'Sharqia'), ('asyut', 'Asyut'), ('aswan', 'Aswan'), ('beni_suef', 'Beni Suef'), ('port_said', 'Port Said'), ('red_sea', 'Red Sea'), ('sohag', 'Sohag'), ('south_sinai', 'South Sinai'), ('new_valley', 'New Valley'), ('matruh', 'Matruh'), ('north_sinai', 'North Sinai'), ('beheira', 'Beheira')], max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=250)),
                ('num_of_members', models.DecimalField(decimal_places=0, default=3, max_digits=10, validators=[django.core.validators.MinValueValidator(3)])),
                ('time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='event.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event.place')),
            ],
        ),
    ]
