# Generated by Django 5.1.1 on 2024-09-18 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_fees_event_is_online_event_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='desc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='place',
            name='governrate',
            field=models.CharField(choices=[('cairo', 'Cairo'), ('alexandria', 'Alexandria'), ('giza', 'Giza'), ('suez', 'Suez'), ('dakahlia', 'Dakahlia'), ('damietta', 'Damietta'), ('faiyum', 'Faiyum'), ('gharbia', 'Gharbia'), ('ismailia', 'Ismailia'), ('kafr_el_sheikh', 'Kafr El Sheikh'), ('minya', 'Minya'), ('monufia', 'Monufia'), ('qalyubia', 'Qalyubia'), ('qena', 'Qena'), ('sharqia', 'Sharqia'), ('asyut', 'Asyut'), ('aswan', 'Aswan'), ('beni_suef', 'Beni Suef'), ('port_said', 'Port Said'), ('red_sea', 'Red Sea'), ('sohag', 'Sohag'), ('south_sinai', 'South Sinai'), ('new_valley', 'New Valley'), ('matruh', 'Matruh'), ('north_sinai', 'North Sinai'), ('beheira', 'Beheira'), ('online', 'Online')], max_length=250),
        ),
    ]
