# Generated by Django 5.1.1 on 2024-09-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_place_desc_alter_place_governrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
